language: python

python:
- '3.6'
services:
- postgresql

install:
- pip install pipenv --upgrade-strategy=only-if-needed
- pipenv install
before_script:
- psql -c 'create database test_db;' -U postgres

script:
- python manage.py test

deploy:
  provider: heroku
  app: still-sea-47042
  api-key:
    secure: xb5xakjOyR3TWxZ/eYTyaHDQYkciht9jBaZ6oYymMQnI/O60COJCQt2S6sMzJdg025lj7YLBTnwivphTpW6syJUe/Dz0Wzv8yoN4zeYibnPsWvMp1M8+6u9Vj25Sti3NlipopWUCir66CdshnnkN7v/oHSnkCs8OHZib1eCvzpZglicBKJtqDCs2ju8SAI302j45FIR3g6KNADMMZKWFcr2NHNQ1KlrIJY5Yd0kib6YFdI0V9Vh0J3fb5KMmRaf9XQFid+N2vbDf+2aHj+xUO044bT+reKV8cRFyVKqyIo2StbIe9FVbD0HjUK6YAT6OlZCWiXELgCXemb0n8MRxcopZ0ob7VJhPLO03cZbKRpeDrAO0S6o4KF8HR3ZT87uR5mMRo1+/l6Khn9UvoLRQH57Mvm4SiuzIgmNtJ/vH6t6pdF6i5J2l0jRt80+achPSPGUZDjF0d/zbLz6TOyniHDKiRBlxi79b25FNftzzS7IyK+V6K048JXhqjsbbV+3NgeSsPLvkbHP6eVUvUx0AFtJed2kcNhGXFMYdNjS9bkjHBVSD9/s4UjCgOPknpk869eOZXWXMUXxvwdr4K5l79PaEIMQm7G6bg7d+ShO7u9nTiRx5QIHDam71u3chhhtSBduh4R/DNCZCkVv0XO2H6sr2YmmQv8pf4YiaqskNh8U=
  run:
  - python manage.py migrate
