language: python

python:
- '3.6'
services:
- postgresql

install:
- pip install pipenv --upgrade-strategy=only-if-needed
- pip install coverage
- pip install codecov
- pipenv install
before_script:
- psql -c 'create database test_db;' -U postgres

script:
- python manage.py test callcenter/tests/
- coverage run manage.py test callcenter/tests/

after_success:
- codecov --gcov-glob callcenter/schemas.py

deploy:
  - provider: releases
    api_key:
      secure: igNKkS/vFkIBRVAf0NYw2huZhnEe/1mcUUua9EDALItgF+8GAib9T37I0LTXBXMEUh0gn+SnDaARs25f19GFA6YS9z1IlHKS+xXMZULF5PKwFzixYxHzrfZu7SrJqmnFVnm0JHP4XJMmCGj3TUYzrClxuXOEBxnJ7fG66DrF73U0pxj5hnmBSq+hR3Ob2AcQ44mBJ+wOd0DcvocpDPrKG+w7Mc2x2Zv2X6KYIuKR5ztEb3ph+KhETJMezKtIv00z3sdajA0KOd1Kx8CM6BWU/KEVq0kU/hfXtR14z/TEXppTMgYa99Hcc4wuy7uGbnfxBA8GpEkngOBrkRxRrwCaCiuDv2nmM4AgXi3U7HySy5ZPa8+TOmWHAVqytC5XIaYEeaD5KBfHGWAm/yTaX1YRMCHx64WjRLzL2gtFTrq/RJ50TcXEAPuQxvr0ElTCY5LN8Zo8SBmkiSb2jJnPNQGnTknRtwwBMQ3jxymtts6/Z7E7xDTWAPhUp5GRRfJqWSNeSjaK4ql3h4wS/x3udVaw0ncV0xpGmfUONA6xAZwsYg9uTNmBSCHrLVCY5Sv+pIePoZmp/+hxXjannJEStye6dYzjN0+yommWRbt7OhdDYJ1dOoo2tYv2vz6vB0+WgFf9gzSM180zBy4fTeHfG6BnqB89g7NH23EgdBaCUb+WYn0=
    file: wort-at-olist
    on:
      repo: ikaromn/work-at-olist
    name: Build $(date +'%d.%m.%Y %R')
    skip-cleanup: true
  - provider: heroku
    app: ikaromn-work-at-olist
    api-key:
      secure: xb5xakjOyR3TWxZ/eYTyaHDQYkciht9jBaZ6oYymMQnI/O60COJCQt2S6sMzJdg025lj7YLBTnwivphTpW6syJUe/Dz0Wzv8yoN4zeYibnPsWvMp1M8+6u9Vj25Sti3NlipopWUCir66CdshnnkN7v/oHSnkCs8OHZib1eCvzpZglicBKJtqDCs2ju8SAI302j45FIR3g6KNADMMZKWFcr2NHNQ1KlrIJY5Yd0kib6YFdI0V9Vh0J3fb5KMmRaf9XQFid+N2vbDf+2aHj+xUO044bT+reKV8cRFyVKqyIo2StbIe9FVbD0HjUK6YAT6OlZCWiXELgCXemb0n8MRxcopZ0ob7VJhPLO03cZbKRpeDrAO0S6o4KF8HR3ZT87uR5mMRo1+/l6Khn9UvoLRQH57Mvm4SiuzIgmNtJ/vH6t6pdF6i5J2l0jRt80+achPSPGUZDjF0d/zbLz6TOyniHDKiRBlxi79b25FNftzzS7IyK+V6K048JXhqjsbbV+3NgeSsPLvkbHP6eVUvUx0AFtJed2kcNhGXFMYdNjS9bkjHBVSD9/s4UjCgOPknpk869eOZXWXMUXxvwdr4K5l79PaEIMQm7G6bg7d+ShO7u9nTiRx5QIHDam71u3chhhtSBduh4R/DNCZCkVv0XO2H6sr2YmmQv8pf4YiaqskNh8U=
    run:
    - python manage.py migrate
    - python manage.py collectstatic --noinput