version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - HOST=db
      - NAME=postgres
      - USER=postgres
      - PASSWORD=root
      - PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db