# Generated by Django 2.0.6 on 2018-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_auto_20180623_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='type',
            field=models.IntegerField(choices=[(1, 'start'), (2, 'end')]),
        ),
    ]
