# Generated by Django 2.0.7 on 2018-07-04 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0005_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fk_call_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 3, 42, 33, 156609, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='fk_call_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 3, 42, 47, 755739, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
