# Generated by Django 2.0.7 on 2018-07-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0006_auto_20180704_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
