# Generated by Django 2.0.7 on 2018-07-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0007_auto_20180705_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.IntegerField(choices=[(1, 'standart'), (2, 'reduced')], unique=True)),
                ('fixed_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('call_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_period', models.TimeField()),
                ('end_period', models.TimeField()),
            ],
            options={
                'verbose_name': 'Price rule',
                'verbose_name_plural': 'Price rules',
            },
        ),
    ]
