# Generated by Django 2.0.7 on 2018-07-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0008_pricerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='call_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='call_charge',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='fixed_charge',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
