# Generated by Django 2.0.7 on 2018-07-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0009_auto_20180708_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='call_duration',
        ),
    ]
