# Generated by Django 2.0.6 on 2018-06-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(null=True)),
                ('call_id', models.IntegerField()),
                ('source', models.CharField(max_length=13)),
                ('destination', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Call Record',
                'verbose_name_plural': 'Call Records',
            },
        ),
    ]
