# Generated by Django 2.0.6 on 2018-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
