# Generated by Django 2.0.6 on 2018-06-26 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20180624_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_duration', models.TimeField()),
                ('call_cost', models.FloatField()),
                ('call_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='hello.CallRecord')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
